### ISSUE TITLE
[Enhancement] RTS style Resource display?

### ISSUE THREAD

**Issue by credomane** [canidae/factorio#12]
It would be nice, especially for the early game, to have a customizeable list of items to track. Kinda like YARM. Seeing as the game can have multiple robot networks only the "starter" robot network would be tracked.

I would find it super handy to always know my count of transport belts, inserters and assemblers without having to manually check. Nothing like starting a project only to discover you have half the required materials and need to shift assemblers around some more first.

**Comment by canidae** [comment]
My first thought is that this is better solved with a mod than baked into the scenario (and as items will be placed in logistic chests you'll easily get a tally of stored items, even though that won't be a filtered list). I'll let the issue stay open to give it some further thought, but it's likely that I'll close it (although I still appreciated the suggestion).

**Comment by canidae** [comment]
I still believe this is better solved using a mod, so I'll close this suggestion.
