### ISSUE TITLE
Typo in on_entity_died event function.

### ISSUE THREAD

**Issue by credomane** [canidae/factorio#13]
The main roboport is defined as "config.roboport" but [here](https://github.com/canidae/factorio/blob/master/brave-new-world/scenarios/bnw/control.lua#L621) it is checked as "config.robport". Losing even the starter roboport doesn't actually lose the game as a result.

**Comment by canidae** [comment]
Doh!

**Comment by canidae** [comment]
Will be fixed in the next version of BNW, thanks.
