### ISSUE TITLE
Not searching localised tech names

### ISSUE THREAD

**Issue by MatthewSmit** [canidae/factorio#3]
The search functionality only searches the key of the technology, which can make it difficult to search for certain technology. My proposed fix is to also search the localised name for a match. This should probably also be implemented for the names of the effects/recipes too.

**Comment by canidae** [comment]
Sorry about the late reply. Didn't realize people actually watched this repo.
This is actually something I can't do, the game prevents it. In multiplayer games it would cause a desync, so the API disallows it.
