### ISSUE TITLE
[auto-stock] Crash while adding new logistics request

### ISSUE THREAD

**Issue by dgw** [canidae/factorio#4]
For some reason the most recent time I went into the logistics request tab to add a temporary request for an item (not an item set in `Auto trash`), the game crashed with an error from auto-stock. This is the first occurrence in probably a week of having the mod installed, so it's likely some kind of race condition or other edge case…

Here's the log info:

````
3474.684 Error MainLoop.cpp:943: Exception at tick 38946816: Error while running event auto-stock::on_tick (ID 0)
Item stack count has to a be positive number
stack traceback:
	__auto-stock__/control.lua:70: in function <__auto-stock__/control.lua:1>
````

Environment: Factorio 0.15.23 on Windows 7 x64 running auto-stock 2.0.0; [mod-list.json](https://github.com/canidae/factorio/files/1107608/mod-list.json.txt) attached.

**Comment by canidae** [comment]
Sorry about the late reply. Didn't realize people actually watched this repo.
Thanks for the report. Never seen this myself and I'm really curious how you managed to get a negative stack count. Unless I abandon the mod I'll take a look at it when I update it for 0.16.

**Comment by canidae** [comment]
I've uploaded a version for 0.16 that should fix this issue. Thanks for reporting!

**Comment by dgw** [comment]
Glad to know you're not abandoning the mod, @canidae. :) That's one more step on the way to migrating my big ol' base to the new Factorio.
